In [48]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import seaborn as sns
sns.set()

In [49]:
data = pd.read_csv('1.02. Multiple linear regression.csv')
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [50]:
y = data['GPA']
x = data.drop(['GPA'], axis=1)

### Standardization

In [51]:
from sklearn.preprocessing import StandardScaler

In [52]:
scaler = StandardScaler()

In [53]:
#scaling mechanism
scaler.fit(x)

StandardScaler()

In [54]:
#standardizing the data and saving it in a variable
x_scaled = scaler.transform(x)
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

In [55]:
reg = LinearRegression()

In [56]:
reg.fit(x_scaled, y)

LinearRegression()

In [57]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [58]:
reg.intercept_

3.330238095238095

In [59]:
summary_table = pd.DataFrame([['Intercept'], ['Coefficient'], ['Rand 1,2,3']], columns=['Features'])
summary_table

Features
0    Intercept
1  Coefficient
2   Rand 1,2,3

In [60]:
new_data = pd.DataFrame(data=[[1700,2],[1900,1]], columns=['SAT', 'Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1900           1

In [61]:
reg.predict(new_data)

/Users/neil.bennett876/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:443: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([295.39979563, 329.76960424])

#### Incorrect results are obtained as the data needs to be scaled, as the model was trained on scaled data.

In [62]:
#Scaling new data
new_scaled_data = scaler.transform(new_data)

In [63]:
reg.predict(new_scaled_data)

array([3.09051403, 3.42949221])

Removing the Rand 1,2,3 variable

In [64]:
#New linear regression containing only SAT values for the independent variable
new_reg = LinearRegression()

In [69]:
#creating a variable containing only scaled SAT values (NO Rand 1,2,3 values)
new_x = x_scaled[:,0].reshape(-1,1)

In [70]:
#Fitting the new regression with the newly scaled data and the dependent variable
new_reg.fit(new_x, y)

LinearRegression()

In [73]:
#Taking only the SAT data from the test data created above, shaping it into a 2D nparray
#And running those values in the newly created Linear regression
only_sat_scale = new_scaled_data[:,0].reshape(-1,1)
new_reg.predict(only_sat_scale)

array([3.08970998, 3.42084759])

In [77]:
new_data['Predicted GPA'] = new_reg.predict(only_sat_scale)
new_data

SAT  Rand 1,2,3  Predicted GPA
0  1700           2       3.089710
1  1900           1       3.420848